    
version: 0.0
os: linux

files:
#donde se encuentran los archivos
  - source: /
    destination: /var/nodeapp/
    #donde los dejaremos, por eso los scripts siempre hacen cd /var/nodeapp
    #los hooks se autoexplican
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300